/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Структура курсу',
    },
    {
      type: 'category',
      label: 'HTML',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Модуль 1',
          items: [
            {
              type: 'category',
              label: 'Заняття 1: HTML частина 1',
              items: [
                {
                  type: 'doc',
                  id: 'HTML/Module--1-1/html',

                  label: 'Веб-технології',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--1-1/tags',
                  label: 'Теги та атрибути',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--1-1/html-structure',
                  label: 'Скелет HTML-документа',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--1-1/semantics',
                  label: 'Семантика',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--1-1/text-styling',
                  label: 'Розмітка тексту',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--1-1/images',
                  label: 'Зображення',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--1-1/structured-markup',
                  label: 'Структурна розмітка',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--1-1/validation',
                  label: 'Валідація',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--1-1/developer-tools',
                  label: 'Інструменти розробника',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--1-1/code-style-guide',
                  label: 'Оформлення коду',
                },
              ],
            },
            {
              type: 'category',
              label: 'Заняття 2: HTML частина 2',
              items: [
                {
                  type: 'doc',
                  id: 'HTML/Module--1-2/tables',
                  label: 'Таблиці',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--1-2/text-markup',
                  label: 'Розмітка тексту',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--1-2/html-symbols',
                  label: 'Символьні підстановки',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--1-2/video-audio',
                  label: 'Відео та аудіо',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Модуль 2',
          items: [
            {
              type: 'category',
              label: 'Заняття 3: Селектори та колір',
              items: [
                {
                  type: 'doc',
                  id: 'HTML/Module--2-1/css-intro',

                  label: 'Вступ до CSS',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--2-1/selectors',

                  label: 'Селектори',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--2-1/pseudoclasses',

                  label: 'Псевдокласи стану',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--2-1/color',

                  label: 'Робота з кольором',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--2-1/cascade',

                  label: 'Каскад стилів',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--2-1/css-variables',

                  label: 'CSS-змінні',
                },
              ],
            },
            {
              type: 'category',
              label: 'Заняття 4: Текст та шрифт',
              items: [
                {
                  type: 'doc',
                  id: 'HTML/Module--2-2/text-styling',

                  label: 'Оформлення тексту',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--2-2/text-props',

                  label: 'Властивості шрифту',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--2-2/text-pseudoelements',

                  label: 'Псевдоелементи тексту',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--2-2/unique-fonts',

                  label: 'Нестандартні шрифти',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Модуль 8',
          items: [
            {
              type: 'category',
              label: 'Заняття 15: Адаптивна верстка',
              items: [
                {
                  type: 'doc',
                  id: 'HTML/Module--8/Lesson--15/media-queries',

                  label: 'Медіа-запити',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--8/Lesson--15/viewport-metatag',

                  label: 'Метатег viewport',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--8/Lesson--15/dev-tools',

                  label: 'Інструменти розробника',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--8/Lesson--15/markup-types',

                  label: 'Типи верстки',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--8/Lesson--15/mobile-first-strategy',

                  label: 'Стратегія Mobile First',
                },
              ],
            },
            {
              type: 'category',
              label: 'Заняття 16: Апаптивна графіка',
              items: [
                {
                  type: 'doc',
                  id: 'HTML/Module--8/Lesson--16/pixel-density',

                  label: 'Щільність пікселів',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--8/Lesson--16/responsive-images',

                  label: 'Респонсивні зображення',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--8/Lesson--16/responsive-background-images',

                  label: 'Респонсивні фонові зображення',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--8/Lesson--16/responsive-img-element',

                  label: 'Респонсивний елемент <img>',
                },
                {
                  type: 'doc',
                  id: 'HTML/Module--8/Lesson--16/picture-element',

                  label: 'Елемент <picture>',
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
